{{default replicas="1"}}
kind: Deployment
apiVersion: apps/v1 
metadata:
  lables:
    app: {{name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
    spec:
      serviceAccount: {{name}}
      containers:
      - name: {{name}}
        env:
        - name: NAMESPACE
          value: {{namespace}}
        {{#each env}}
        - name: {{@key}}
          value: {{this}}
        {{/each}}
        imagePullPolicy: IfNotPresent
        image: {{image}}:{{tag}}
        ports:
        {{#each ports as |p k|}}
        - containerPort: {{p.port}}
          name: {{k}}
        {{/each}}